swagger: "2.0"
info: {}
basePath: /v1
paths:
  /chat/:
    get:
      tags:
      - chat
      description: get all Chats
      operationId: ChatController.GetAll
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.Chats'
    post:
      tags:
      - chat
      description: create message
      operationId: ChatController.CreateChatMessage
      parameters:
      - in: body
        name: body
        description: body for user content
        required: true
        schema:
          $ref: '#/definitions/requests.Chat'
      responses:
        "201":
          description: ""
        "403":
          description: ': requests.Chat is empty'
        "500":
          description: internal server error
  /chat/{id}:
    get:
      tags:
      - chat
      description: get chat by id
      operationId: ChatController.Get
      parameters:
      - in: path
        name: id
        description: "true"
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/responses.Chat'
        "403":
          description: :id is empty
        "404":
          description: :chat is not found
    put:
      tags:
      - chat
      description: update the chat
      operationId: ChatController.Update
      parameters:
      - in: path
        name: id
        description: "true"
        type: string
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/requests.UpdateChat'
      responses:
        "201":
          description: ""
        "403":
          description: :id is not int
        "500":
          description: internal server error
    delete:
      tags:
      - chat
      description: delete the chat
      operationId: ChatController.Delete
      parameters:
      - in: path
        name: id
        description: "true"
        type: string
      responses:
        "201":
          description: ""
        "403":
          description: id is empty
        "500":
          description: internal server error
definitions:
  requests.Chat:
    title: Chat
    type: object
    properties:
      message:
        type: string
      user_name:
        type: string
  requests.UpdateChat:
    title: UpdateChat
    type: object
    properties:
      message:
        type: string
  responses.Chat:
    title: Chat
    type: object
    properties:
      id:
        type: integer
        format: int64
      message:
        type: string
      user_name:
        type: string
  responses.Chats:
    title: Chats
    type: object
    properties:
      chats:
        type: array
        items:
          $ref: '#/definitions/responses.Chat'
